In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import Input
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [3]:
# Carga de datos
# Modificar la ruta a la ubicacion del dataset
df = pd.read_excel("C:\\Users\\USER\\Downloads\\base-de-datos-violencia-intrafamiliar-ano-2024_v3.xlsx")
df.head()

,HEC_DIA,HEC_MES,HEC_ANO,HEC_DEPTO,HEC_DEPTOMCPIO,HEC_TIPAGRE,NUMERO_BOLETA,DIA_EMISION,MES_EMISION,ANO_EMISION,...,ARTICULOCODPEN2,ARTICULOCODPEN3,ARTICULOCODPEN4,ARTICULOTRAS1,ARTICULOTRAS2,ARTICULOTRAS3,ARTICULOTRAS4,MEDIDAS_SEGURIDAD,TIPO_MEDIDA,ORGANISMO_REMITE
0,4,11,2024,1,110,1122,367,4,11,2024,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,24,3,2024,2,202,1222,5,25,3,2024,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,IJ,18.0
2,99,99,9999,1,101,1122,430,2,3,2024,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,28,3,2024,2,202,1122,6,28,3,2024,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,AIJ,18.0
4,12,7,2024,7,706,2122,16,24,7,2024,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,IJ,18.0

In [4]:
print("Original rows:", df.shape[0])

# Violencia fisica =1 , no fisica = 2
physical_aggression_codes = [1222, 2212, 1122,1212,1221,2211,1112,1121,1211,1111]
df["TARGET_PHYSICAL"] = df["HEC_TIPAGRE"].apply(
    lambda x: 1 if x in physical_aggression_codes else 0
)
df.head()

Original rows: 36609

,HEC_DIA,HEC_MES,HEC_ANO,HEC_DEPTO,HEC_DEPTOMCPIO,HEC_TIPAGRE,NUMERO_BOLETA,DIA_EMISION,MES_EMISION,ANO_EMISION,...,ARTICULOCODPEN3,ARTICULOCODPEN4,ARTICULOTRAS1,ARTICULOTRAS2,ARTICULOTRAS3,ARTICULOTRAS4,MEDIDAS_SEGURIDAD,TIPO_MEDIDA,ORGANISMO_REMITE,TARGET_PHYSICAL
0,4,11,2024,1,110,1122,367,4,11,2024,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1,24,3,2024,2,202,1222,5,25,3,2024,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,IJ,18.0,1
2,99,99,9999,1,101,1122,430,2,3,2024,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
3,28,3,2024,2,202,1122,6,28,3,2024,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,AIJ,18.0,1
4,12,7,2024,7,706,2122,16,24,7,2024,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,IJ,18.0,0

In [14]:

predictors = df[[
    "VIC_SEXO", "VIC_EDAD", "VIC_ALFAB", "VIC_ESCOLARIDAD",
    "VIC_EST_CIV", "VIC_TRABAJA", "VIC_OCUP",
    "AGR_SEXO", "AGR_EDAD", "AGR_TRABAJA", "AGR_OCUP",
    "VIC_REL_AGR",
    "OTRAS_VICTIMAS"
]].dropna()

print("Rows:", predictors.shape[0])

Rows: 10803

In [15]:
model_data = predictors.copy()
model_data["TARGET_PHYSICAL"] = df.loc[predictors.index, "TARGET_PHYSICAL"]

X = model_data.drop(columns=["TARGET_PHYSICAL"])
y = model_data["TARGET_PHYSICAL"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.30, random_state=123, stratify=y
)

In [16]:
input_dim = X_train.shape[1]

model = Sequential([
    Input(shape=(input_dim,)),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

history = model.fit(
    X_train, y_train,
    epochs=60,
    batch_size=64,
    validation_data=(X_test, y_test)
)

loss, accuracy = model.evaluate(X_test, y_test)
print(f"\nLoss: {loss:.4f}, Accuracy: {accuracy:.4f}")

Epoch 1/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.5454 - loss: 139.3351 - val_accuracy: 0.4054 - val_loss: 41.6955
Epoch 2/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.5475 - loss: 51.3803 - val_accuracy: 0.4030 - val_loss: 24.3460
Epoch 3/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.5320 - loss: 25.6190 - val_accuracy: 0.6316 - val_loss: 5.8470
Epoch 4/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.5249 - loss: 10.9454 - val_accuracy: 0.5035 - val_loss: 1.4328
Epoch 5/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.5386 - loss: 7.3425 - val_accuracy: 0.6316 - val_loss: 3.3891
Epoch 6/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.5276 - loss: 5.2498 - val_accuracy: 0.6057 - val_loss: 0.8272
Epoch 7/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.5459 - loss: 4.9674 - val_accuracy: 0.6316 - val_loss: 2.8085
Epoch 8/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.5339 - loss: 3.2437 - val_accuracy: 0.3733 - val_loss: 4.7748
Epoch 9/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.5402 - loss: 4.5599 - val_accuracy: 0.6316 - val_loss: 3.6118
Epoch 10/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.5385 - loss: 2.2411 - val_accuracy: 0.6316 - val_loss: 3.2647
Epoch 11/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.5418 - loss: 3.1987 - val_accuracy: 0.3823 - val_loss: 1.1399
Epoch 12/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.5372 - loss: 2.0807 - val_accuracy: 0.4091 - val_loss: 1.9553
Epoch 13/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.5488 - loss: 1.9890 - val_accuracy: 0.4625 - val_loss: 0.8847
Epoch 14/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.5369 - loss: 2.2015 - val_accuracy: 0.6310 - val_loss: 1.9660
Epoch 15/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.5353 - loss: 2.0676 - val_accuracy: 0.5733 - val_loss: 1.0472
Epoch 16/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.5387 - loss: 1.6304 - val_accuracy: 0.3703 - val_loss: 3.4769
Epoch 17/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.5341 - loss: 1.7007 - val_accuracy: 0.5619 - val_loss: 0.7108
Epoch 18/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.5284 - loss: 1.6964 - val_accuracy: 0.6313 - val_loss: 1.2027
Epoch 19/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.5479 - loss: 1.2371 - val_accuracy: 0.6316 - val_loss: 1.9981
Epoch 20/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.5399 - loss: 1.2935 - val_accuracy: 0.6316 - val_loss: 1.0684
Epoch 21/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.5402 - loss: 1.7284 - val_accuracy: 0.4064 - val_loss: 0.9924
Epoch 22/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.5368 - loss: 1.4036 - val_accuracy: 0.6075 - val_loss: 0.6951
Epoch 23/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.5451 - loss: 1.2567 - val_accuracy: 0.6313 - val_loss: 0.7273
Epoch 24/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.5341 - loss: 1.4282 - val_accuracy: 0.3690 - val_loss: 1.8955
Epoch 25/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.5304 - loss: 1.4704 - val_accuracy: 0.6307 - val_loss: 1.5250
Epoch 26/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.5421 - loss: 1.1873 - val_accuracy: 0.6319 - val_loss: 0.7005
Epoch 27/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.5619 - loss: 1.0058 - val_accuracy: 0.3875 - val_loss: 0.8506
Epoch 28/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.5417 - loss: 1.0487 - val_accuracy: 0.5730 - val_loss: 0.8205
Epoch 29/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.5432 - loss: 0.9989 - val_accuracy: 0.6307 - val_loss: 0.6849
Epoch 30/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.5600 - loss: 0.9449 - val_accuracy: 0.6316 - val_loss: 0.9096
Epoch 31/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.5628 - loss: 0.8735 - val_accuracy: 0.3696 - val_loss: 0.7513
Epoch 32/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.5483 - loss: 0.9579 - val_accuracy: 0.6316 - val_loss: 0.7545
Epoch 33/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.5623 - loss: 0.8382 - val_accuracy: 0.6297 - val_loss: 0.6892
Epoch 34/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.5676 - loss: 0.8302 - val_accuracy: 0.6313 - val_loss: 1.1637
Epoch 35/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.5524 - loss: 0.8280 - val_accuracy: 0.4727 - val_loss: 0.7064
Epoch 36/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.5553 - loss: 0.8752 - val_accuracy: 0.6304 - val_loss: 0.7013
Epoch 37/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.5546 - loss: 0.8423 - val_accuracy: 0.3940 - val_loss: 0.8356
Epoch 38/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.5526 - loss: 0.8456 - val_accuracy: 0.4764 - val_loss: 0.7868
Epoch 39/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.5513 - loss: 0.8225 - val_accuracy: 0.4249 - val_loss: 0.7845
Epoch 40/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.5823 - loss: 0.7579 - val_accuracy: 0.6310 - val_loss: 0.6623
Epoch 41/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.5721 - loss: 0.7733 - val_accuracy: 0.6304 - val_loss: 0.6885
Epoch 42/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.5763 - loss: 0.7451 - val_accuracy: 0.6131 - val_loss: 0.6690
Epoch 43/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.5796 - loss: 0.7427 - val_accuracy: 0.6316 - val_loss: 0.6685
Epoch 44/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.5969 - loss: 0.7264 - val_accuracy: 0.6307 - val_loss: 0.7002
Epoch 45/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.5783 - loss: 0.7289 - val_accuracy: 0.6307 - val_loss: 0.7028
Epoch 46/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.6025 - loss: 0.7253 - val_accuracy: 0.6316 - val_loss: 0.6746
Epoch 47/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.5932 - loss: 0.7223 - val_accuracy: 0.6310 - val_loss: 0.6583
Epoch 48/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.5996 - loss: 0.7267 - val_accuracy: 0.5881 - val_loss: 0.6856
Epoch 49/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.5940 - loss: 0.7170 - val_accuracy: 0.5881 - val_loss: 0.6792
Epoch 50/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.5977 - loss: 0.7184 - val_accuracy: 0.6310 - val_loss: 0.6697
Epoch 51/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.6043 - loss: 0.6991 - val_accuracy: 0.4613 - val_loss: 0.7147
Epoch 52/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6030 - loss: 0.7050 - val_accuracy: 0.4520 - val_loss: 0.6992
Epoch 53/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6053 - loss: 0.7116 - val_accuracy: 0.6316 - val_loss: 0.6638
Epoch 54/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6197 - loss: 0.6959 - val_accuracy: 0.6316 - val_loss: 0.6564
Epoch 55/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6152 - loss: 0.6890 - val_accuracy: 0.6307 - val_loss: 0.6636
Epoch 56/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6185 - loss: 0.6923 - val_accuracy: 0.6276 - val_loss: 0.6670
Epoch 57/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6173 - loss: 0.6892 - val_accuracy: 0.6294 - val_loss: 0.6614
Epoch 58/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.6243 - loss: 0.6849 - val_accuracy: 0.6245 - val_loss: 0.6723
Epoch 59/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6160 - loss: 0.6799 - val_accuracy: 0.6310 - val_loss: 0.6588
Epoch 60/60
119/119 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6291 - loss: 0.6758 - val_accuracy: 0.6316 - val_loss: 0.6606
102/102 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6316 - loss: 0.6606

Loss: 0.6606, Accuracy: 0.6316

In [18]:

# prediccion individual
new_case = pd.DataFrame([{
    "VIC_SEXO": 2, # mujer
    "VIC_EDAD": 28,
    "VIC_ALFAB": 1, # alfabeta
    "VIC_ESCOLARIDAD": 59, # universitario
    "VIC_EST_CIV": 2, # casada
    "VIC_TRABAJA": 2, # No trabaja por un salario o ingreso
    "VIC_OCUP": 2631, # economistas
    "AGR_SEXO": 1, # Hombre
    "AGR_EDAD": 30,
    "AGR_TRABAJA": 1, # si trabaja por un salario o ingreso
    "AGR_OCUP": 2141,
    "VIC_REL_AGR": 1, # esposo
    "OTRAS_VICTIMAS": 0
}])

new_case = new_case[X_train.columns]

prob = model.predict(new_case)[0][0]
prediction = 1 if prob >= 0.5 else 0

print("\nProbabilidad prevista de violencia FÍSICA:", prob)
print("Clase prevista (0=no física, 1=física):", prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step

Probabilidad prevista de violencia FÍSICA: 0.43097353
Clase prevista (0=no física, 1=física): 0